events {
    worker_connections 1024;
}

http {
    client_max_body_size 50M;
    resolver 127.0.0.11 valid=30s;

    server {
        listen 8080;

        location / {
            set $upstream_web http://web:3000;
            proxy_pass $upstream_web;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # Backend Auth Routes called from client
        location /api/auth/register {
            set $upstream_api http://api:3001;
            proxy_pass $upstream_api;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/auth/refresh {
            set $upstream_api http://api:3001;
            proxy_pass $upstream_api;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # NextAuth Routes (handled by Next.js)
        location /api/auth {
            set $upstream_web http://web:3000;
            proxy_pass $upstream_web;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # All other API Routes (handled by Backend)
        location /api {
            set $upstream_api http://api:3001;
            proxy_pass $upstream_api;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_read_timeout 300s;
            proxy_connect_timeout 300s;
        }
    }
}